[package]
name = "ikra-pdf-editor"
version = "2.0.0"
edition = "2024"
authors = ["Md Abu Hanif>"]
description = "Professional PDF Editor built with Rust"
license = "MIT"

[[bin]]
name = "ikra"
path = "src/main.rs"

[dependencies]
eframe = { version = "0.29", features = ["default_fonts", "wgpu"] }
egui = "0.29"
pdfium-render = { version = "0.8", features = ["image", "thread_safe"] }
image = { version = "0.25", default-features = false, features = ["png"] }
rfd = "0.14"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
lopdf = "0.32"
uuid = { version = "1", features = ["v4"] }
lazy_static = "1.5.0"
rayon = "1.8"
egui_extras = { version = "0.29", features = ["svg", "image"] }

[build-dependencies]
winres = "0.1"


[package.metadata.deb]
maintainer = "Md Abu Hanif>"
assets = [
    ["target/release/ikra", "usr/bin/ikra", "755"],
    ["assets/ikra.png", "usr/share/pixmaps/ikra.png", "644"]
]

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/ikra", dest = "/usr/bin/ikra", mode = "755" },
    { source = "assets/ikra.png", dest = "/usr/share/pixmaps/ikra.png", mode = "644" }
]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true # Automatically strips the binary, making manual `strip` steps redundant